### PR TITLE
Make import fail for undefined symbols (fixes #631)

### LINKED ISSUE #631: Import should fail if a symbol isn't defined
At the moment `(import foo '[bar] :unqualified)` will succeed even if `bar` is not defined/exported by `foo`.

### PR DESCRIPTION
**Pull request by curiousleo**
Fixes #631.

### CODE REVIEW

File: src/Radicle/Internal/PrimFns.hs [hunk 1]
```diff
@@ -709,8 +709,10 @@ purePrimFns = fromList $ allDocs $
           let allMod = fromEnv e
           toImport <- case v_ of
                 Just vs -> do
-                  is <- Protolude.toList <$> traverse isAtom vs ?? toLangError (OtherError "import: must be given a vector of symbols to import")
-                  pure $ Map.restrictKeys allMod (Set.fromList is)
+                  is <- Set.fromList <$> Protolude.toList <$> traverse isAtom vs ?? toLangError (OtherError "import: must be given a vector of symbols to import")
```
Comment (curiousleo) [inline src/Radicle/Internal/PrimFns.hs]: First converting to a list and then to a set is awkward, but I couldn't find any builtin to convert Seq to Set directly.

File: src/Radicle/Internal/PrimFns.hs [hunk 2]
```diff
@@ -709,8 +709,10 @@ purePrimFns = fromList $ allDocs $
...
+                  if Set.null (is Set.\\ Map.keysSet allMod)
```
Comment (curiousleo) [inline src/Radicle/Internal/PrimFns.hs]: No idea if this `if ... then ... else` is idiomatic here, it's been a while since I've last written any Haskell.

File: src/Radicle/Internal/PrimFns.hs [hunk 3]
```diff
@@ -709,8 +709,10 @@ purePrimFns = fromList $ allDocs $
...
+                    then pure $ Map.restrictKeys allMod is
+                    else throwErrorHere (OtherError "import: cannot import undefined symbols")
```
Comment (curiousleo) [inline src/Radicle/Internal/PrimFns.hs]: This does not tell the user which symbols were undefined - that's something that could be added.

Comment (jkarni) [reply src/Radicle/Internal/PrimFns.hs]: Maybe:

```
                  let missing = is Set.\\ Map.keysSet allMod
                  if Set.null missing
                    then pure $ Map.restrictKeys allMod is
                    else throwErrorHere
                       $ OtherError
                       $ "import: cannot import undefined symbols: "
                         <> T.intercalate ", " (fromIdent <$> Set.toList missing)
```

File: src/Radicle/Internal/PrimFns.hs (hunk 1 above)
Comment (jkarni) [reply src/Radicle/Internal/PrimFns.hs]: I think that's fine

File: src/Radicle/Internal/PrimFns.hs (hunk 2 above)
Comment (jkarni) [reply src/Radicle/Internal/PrimFns.hs]: Yup - looks good.

File: src/Radicle/Internal/PrimFns.hs (hunk 3 above)
Comment (jkarni) [reply src/Radicle/Internal/PrimFns.hs]: Somehow I missed this comment:

The corresponding test (in `test/spec/Radicle/Tests.hs`, around ln 560), would be:

```
    , testCase "Importing complains if imports are undefined" $ do
        let prog = [s|(module
                        {:module 'foo :doc "" :exports '[x]}
                        (def x 1))
                      (import foo '[b a])
                      |]
        prog `failsWith` OtherError "import: cannot import undefined symbols: a, b"
```

Comment (curiousleo) [reply src/Radicle/Internal/PrimFns.hs]: Wow, thanks!

I've adjusted your suggestions slightly:
- The list of problematic imports now appears sorted in the error message to make it "more deterministic" (I think alphabetic sorts depend on environment variables related to language settings like `LC_ALL`, but I don't think that's a big issue).
- I've amended the test case to also include the case where a symbol is neither defined nor exported.

File: bin/rad-project [hunk 4]
```diff
@@ -13,7 +13,7 @@
 (import prelude/cmd-parsing :unqualified)
 (import prelude/io :as 'io)
 (import prelude/io-utils
-  '[set-git-config get-git-config process-git-with-exit!]
+  '[set-git-config! get-git-config! process-git-with-exit!]
```
Comment (curiousleo) [inline bin/rad-project]: The changes in this PR surfaced these two typos. I'm a bit confused how the code in `rad-project` was able to run with the erroneous imports.

File: src/Radicle/Internal/PrimFns.hs [hunk 5]
```diff
@@ -709,8 +709,14 @@ purePrimFns = fromList $ allDocs $
...
-                  is <- Protolude.toList <$> traverse isAtom vs ?? toLangError (OtherError "import: must be given a vector of symbols to import")
-                  pure $ Map.restrictKeys allMod (Set.fromList is)
+                  is <- (Set.fromList . Protolude.toList <$> traverse isAtom vs) ?? toLangError (OtherError "import: must be given a vector of symbols to import")
+                  let missing = is Set.\\ Map.keysSet allMod
+                  if Set.null missing
+                    then pure $ Map.restrictKeys allMod is
+                    else throwErrorHere
+                      $ OtherError
+                      $ "import: cannot import undefined symbols: "
+                        <> T.intercalate ", " (sort (fromIdent <$> Set.toList missing))
```
Comment (jkarni) [inline src/Radicle/Internal/PrimFns.hs]: `Set.toList` already returns the elements sorted (though you can use `Set.toAscList` to be more explicit), so no need to sort again.

File: bin/rad-project (hunk 4 above)
Comment (jkarni) [reply bin/rad-project]: Ha. Turns out prelude already includes all of `io-utils`, which is why it was working. I can remove that import from prelude (it shouldn't really be there) in a separate PR.

File: src/Radicle/Internal/PrimFns.hs (hunk 5 above)
Comment (curiousleo) [reply src/Radicle/Internal/PrimFns.hs]: Nice! `toAscList` it is.

File: bin/rad-project (hunk 4 above)
Comment (curiousleo) [reply bin/rad-project]: I see!

**Comment by jameshaydon** [comment]
:tada:
